name: get-psyched
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.19932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#556273'
    - '#090909'
    - '#979797'
    - '#262827'
    - '#ffc07b'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
