name: get-psyched
favicon: null
layout_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b3d7ed'
    - '#386f8d'
    - '#192d36'
    - '#673842'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
